### PR TITLE
Cleanup mislabeled BSD license

### PR DESCRIPTION
**Pull request by tfoote**
This was propagated due to an invalid license in ament_lint which is proposed to be fixed at: https://github.com/ament/ament_lint/pull/209

### CODE REVIEW

**Comment by cottsay** [comment]
@tfoote, is the new template going to be added to Dashing and Eloquent? If not, I'll have to create a new branch for Foxy.

**Comment by tfoote** [comment]
Yes is should go into all versions.

**Comment by clalancette** [comment]
@mjeronimo I wanted to revive this PR and get it in finally.  To do that, what I'd like to do here is create a `ros2` branch, which would be the branch that Rolling uses.  Then starting with Humble, we would branch off for each ROS release we do.  That makes it similar to most of the other repositories we have in the ROS 2 core.  What do you think of this plan?

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17450/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11978/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17963/)

**Review by clalancette — APPROVED** [review]

**Pull request merged**
