### PR TITLE
Fix float slider step size

### PR DESCRIPTION
**Pull request by Flova**
Fixes issue #116 

Currently, untested as I am on the go without a working ros2 installation.

### CODE REVIEW

**Comment by Flova** [comment]
I now tested it and it works as intended

### Before:

image

## After:

image

**Review by MatthijsBurgh — APPROVED** [review]

**Review by clalancette — APPROVED** [review]
I can't say I fully understand why this is an improvement, but it is hard to argue with the results and this makes it match the IntegerEditor.  Approving, and I'll run CI on it next.

Note that I also retargeted this to the rolling branch; we can request the bot to backport to 'humble' later.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16894/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11464/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17297/)

**Comment by clalancette** [comment]
@Mergifyio backport humble

**Comment by Flova** [comment]
Thanks for merging the  PR! @clalancette 

Regarding the idea behind the fix:
The QT Slider component is working with integers only. So a mapping is introduced to map the float range to displayed integer values and back in case we have a float param. This mapping also does things like min/max normalisation. The sliders also feature a step size describing the minimum integer step as well as some other steps for page up and down keys and visual tick marks. These steps are all integer values, as the QTSlider only knows integer states. The QT version used in 22.04 drops an autocast which  converted the steps sizes implicitly to integers, resulting in the observed error (the float slider step sizes are defined by a float for ros params). The previous implicit cast resulted in unintended behavior as the float step size was interpreted as integer steps in the QT widget. Now a step size of 0.25 would indeed increase the value in 0.25 steps. The step size for floats is not frequently used imo. and the default value was castable without any weird behaviour so most likely nobody noticed until the cast was removed and the type check failed. 

The fix mainly consists of applying the integer mapping not only to the values, but also to the step size parameter. To do this the code is moved down a bit as the integer mapping is only available later on.

**Comment by clalancette** [comment]
> Regarding the idea behind the fix:

Excellent, thanks for the explanation!

**Comment by christianrauch** [comment]
This indeed fixes #116.

@Flova If you write `Fixes #<ISSUE>`, then this will automatically close the issue once the fix has been merged. (You wrote `Fixes issue #<ISSUE>`, which is not recognised.)

**Pull request merged**
