### PR TITLE
Add support for array types

### LINKED ISSUE #53: Cannot get or set parameters with the type of PARAMETER_INTEGER_ARRAY
I have several parameters whose type are PARAMETER_INTEGER_ARRAY. It seems that rqt_reconfigure hasn't support this type yet, since I was trying to launch rqt_reconfigure, it failed with the following error messages:

> Traceback (most recent call last):
  File "/home/intel/workspace/ros2_other_ws/build/rqt_reconfigure/src/rqt_reconfigure/node_selector_widget.py", line 277, in _selection_changed_slot
    self._selection_selected(index_current, rosnode_name_selected)
  File "/home/intel/workspace/ros2_other_ws/build/rqt_reconfigure/src/rqt_reconfigure/node_selector_widget.py", line 228, in _selection_selected
    raise e
  File "/home/intel/workspace/ros2_other_ws/build/rqt_reconfigure/src/rqt_reconfigure/node_selector_widget.py", line 226, in _selection_selected
    item_widget = item_child.get_param_client_widget()
  File "/home/intel/workspace/ros2_other_ws/build/rqt_reconfigure/src/rqt_reconfigure/treenode_qstditem.py", line 94, in get_param_client_widget
    self._context, self._raw_param_name
  File "/home/intel/workspace/ros2_other_ws/build/rqt_reconfigure/src/rqt_reconfigure/param_client_widget.py", line 116, in __init__
    self._param_client.get_parameters(param_names),
  File "/home/intel/workspace/ros2_other_ws/build/rqt_reconfigure/src/rqt_reconfigure/param_api.py", line 89, in get_parameters
    for name, value in zip(names, get_params_response.values)
  File "/home/intel/workspace/ros2_other_ws/build/rqt_reconfigure/src/rqt_reconfigure/param_api.py", line 89, in <listcomp>
    for name, value in zip(names, get_params_response.values)
  File "/home/intel/workspace/ros2_ws/install/rclpy/lib/python3.6/site-packages/rclpy/parameter.py", line 121, in from_parameter_msg
    return cls(param_msg.name, type_, value)
  File "/home/intel/workspace/ros2_ws/install/rclpy/lib/python3.6/site-packages/rclpy/parameter.py", line 132, in __init__
    raise ValueError("Type '{}' and value '{}' do not agree".format(type_, value))
ValueError: Type 'Type.INTEGER_ARRAY' and value 'array('q', [640, 480])' do not agree
[INFO] [PluginContainerWidget]: Connection to node=/realsense failed:
Type 'Type.INTEGER_ARRAY' and value 'array('q', [640, 480])' do not agree
[ERROR] [rqt_reconfigure]: Connection to node=/realsense failed:
Type 'Type.INTEGER_ARRAY' and value 'array('q', [640, 480])' do not agree

On the other hand, I was trying to get/set parameters by ros2 param. Everything works well.

>$ros2 param set my_node my_param [640,480]
Set parameter successful
>$ros2 param get my_node my_param
Integer values are: array('q', [640, 480])

### PR DESCRIPTION
**Pull request by shrijitsingh99**
Closes #53 and #56

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Could you create a PR for ROS1 too? As it is also missing array support.

**Review by mjeronimo — APPROVED** [review]

**Comment by shrijitsingh99** [comment]
> Could you create a PR for ROS1 too? As it is also missing array support.

 I will try to look into it, though I might not have the cycles available for it and I haven't looked into ROS1 parameters in a while.

**Comment by Flova** [comment]
Any updates on this?

**Comment by shrijitsingh99** [comment]
I don't have the cycles to create a PR for ROS1 at the moment but I think they can be merged in if there are no blockers.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17435/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11960/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17944/)

**Comment by clalancette** [comment]
I rebased this and fixed the small style issues pointed out by CI.  Here's another CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17440/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11965/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17951/)

**Comment by gordon-n-stevenson** [comment]
https://github.com/Mergifyio backport humble

**Pull request merged**
