### PR TITLE
Fix to use English locale in QDoubleValidator

### PR DESCRIPTION
**Pull request by KindDragon**

### CODE REVIEW

**Comment by cottsay** [comment]
How can I reproduce this problem, or what does it look like in the UI?

**Comment by KindDragon** [comment]
Change system locale to Russian (for example) and try to enter dot to DoubleEditor.
DoubleEditor accepts with this locale the only comma as separator, but crash when you try to convert text to `float`.

**Comment by cottsay** [comment]
Thanks, I was able to reproduce the bug and verify your fix, which looks like the right solution for now.

I'm not sure what other packages are doing, but would it be useful for `rqt_reconfigure` to localize these values instead of forcing `C`? It could probably be done with minimal effort.

**Comment by KindDragon** [comment]
> I'm not sure what other packages are doing, but would it be useful for rqt_reconfigure to localize these values instead of forcing C? It could probably be done with minimal effort.

Both variants ok for me. I just decided that it's easier to fix this way

**Pull request merged**
