### PR TITLE
Fixed interfaces icons on Windows and MacOS

### PR DESCRIPTION
**Pull request by ahcorde**
This PR fixes the issues with icons on Windows and MacOS.

According with the [documentation](https://doc.qt.io/qt-5/qicon.html#fromTheme)

>  - Note: By default, only X11 will support themed icons. In order to use themed icons on Mac and Windows, you will have to bundle a compliant theme in one of your themeSearchPaths() and set the appropriate themeName().

Related with this PR https://github.com/ros-visualization/rqt_reconfigure/pull/81

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by cottsay** [comment]
What is the license for these graphics? Also, why aren't we putting them all in a single package and loading them from there?

**Comment by ahcorde** [comment]
> What is the license for these graphics? 

I copied most of them from [gtk](https://commons.wikimedia.org/wiki/GNOME_Desktop_icons) which is GNU General Public License version 2. I will check them again. Should I create a note somewhere with the license?

>  why aren't we putting them all in a single package and loading them from there?

Maybe we can include these Icons in `qt_gui_py_common` which most of the rqt visualization tools depend on

**Comment by cottsay** [comment]
> I copied most of them from gtk which is GNU General Public License version 2. I will check them again. Should I create a note somewhere with the license?

I'm not very savvy with license compatibility, but I know that we need to address this. We cannot distribute GPL material without the corresponding license. Please start a conversation with the team about how to proceed.

**Comment by ahcorde** [comment]
Closing this PR in favour of this other PR https://github.com/ros2/ros2/pull/928

**Pull request closed without merging**
